#!/bin/bash
#SBATCH --job-name=fluidanimate_scalability_pthreads
#SBATCH --time=0-0:40
#SBATCH --cpus-per-task=32
#SBATCH --hint=compute_bound
#SBATCH --mail-user=cadubentzen@gmail.com
#SBATCH --mail-type=ALL

for i in 1 2 3
do
	for j in 1 2 4 8 16 32
	do
		parsecmgmt -a run -p parsec.fluidanimate -c gcc-pthreads -i simlarge -n $j
		parsecmgmt -a run -p parsec.fluidanimate -c gcc-pthreads -i native -n $j
	done
done
