#!/bin/bash
#SBATCH --job-name=fluidanimate_scalability_serial
#SBATCH --time=0-0:25
#SBATCH --hint=compute_bound
#SBATCH --mail-user=cadubentzen@gmail.com
#SBATCH --mail-type=ALL

for i in 1 2 3
do
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-serial -i simmedium
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-serial -i simlarge
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-serial -i native
done
