#!/bin/bash
#SBATCH --job-name=fluidanimate_scalability_pthreads
#SBATCH --time=0-0:25
#SBATCH --cpus-per-task=1
#SBATCH --hint=compute_bound
#SBATCH --mail-user=cadubentzen@gmail.com
#SBATCH --mail-type=ALL

for i in 1 2 3
do
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-pthreads -i simlarge -n 1
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-pthreads -i native -n 1
done
